const fileNames = [
  "README.md",
  "Index.html",
  "App.js",
  "styles.css",
  "index.js",
  "config.json",
  "package.json",
  "server.js",
  "webpack.config.js",
  "babel.config.js",
  "main.js",
  "header.js",
  "footer.js",
  "Sidebar.js",
  "Dashboard.js",
  "login.html",
  "signup.html",
  "reset-password.html",
  "home.css",
  "about.css",
  "README.md",
  "Index.html",
  "App.js",
  "styles.css",
  "index.js",
  "config.json",
  "package.json",
  "server.js",
  "webpack.config.js",
  "babel.config.js",
  "main.js",
  "header.js",
  "footer.js",
  "Sidebar.js",
  "Dashboard.js",
  "login.html",
  "signup.html",
  "reset-password.html",
  "home.css",
  "about.css",
];

const icons = [
  "bi bi-markdown",
  "bi bi-filetype-html",
  "bi bi-filetype-js",
  "bi bi-filetype-css",
  "bi bi-filetype-js",
  "bi bi-filetype-json",
  "bi bi-filetype-json",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-html",
  "bi bi-filetype-html",
  "bi bi-filetype-html",
  "bi bi-filetype-css",
  "bi bi-filetype-css",
  "bi bi-markdown",
  "bi bi-filetype-html",
  "bi bi-filetype-js",
  "bi bi-filetype-css",
  "bi bi-filetype-js",
  "bi bi-filetype-json",
  "bi bi-filetype-json",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-js",
  "bi bi-filetype-html",
  "bi bi-filetype-html",
  "bi bi-filetype-html",
  "bi bi-filetype-css",
  "bi bi-filetype-css",
];

const commitMessages = [
  "initial commit",
  "first file",
  "added app component",
  "added styles",
  "added index",
  "configured project",
  "added package.json",
  "server setup",
  "added webpack config",
  "babel setup",
  "created main.js",
  "header component added",
  "footer component added",
  "sidebar component added",
  "dashboard component created",
  "login page created",
  "signup page created",
  "reset password page added",
  "home page styles",
  "about page styles",
  "initial commit",
  "first file",
  "added app component",
  "added styles",
  "added index",
  "configured project",
  "added package.json",
  "server setup",
  "added webpack config",
  "babel setup",
  "created main.js",
  "header component added",
  "footer component added",
  "sidebar component added",
  "dashboard component created",
  "login page created",
  "signup page created",
  "reset password page added",
  "home page styles",
  "about page styles",
];

const updateTimes = [
  "2 days ago",
  "1 hr ago",
  "30 mins ago",
  "10 mins ago",
  "5 mins ago",
  "3 days ago",
  "2 hrs ago",
  "1 hr ago",
  "50 mins ago",
  "45 mins ago",
  "40 mins ago",
  "35 mins ago",
  "30 mins ago",
  "25 mins ago",
  "20 mins ago",
  "15 mins ago",
  "10 mins ago",
  "5 mins ago",
  "2 mins ago",
  "Just now",
  "2 days ago",
  "1 hr ago",
  "30 mins ago",
  "10 mins ago",
  "5 mins ago",
  "3 days ago",
  "2 hrs ago",
  "1 hr ago",
  "50 mins ago",
  "45 mins ago",
  "40 mins ago",
  "35 mins ago",
  "30 mins ago",
  "25 mins ago",
  "20 mins ago",
  "15 mins ago",
  "10 mins ago",
  "5 mins ago",
  "2 mins ago",
  "Just now",
];

const links = [
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
  "#",
];

export { fileNames, icons, commitMessages, updateTimes, links };
