const repoDetails = [
  {
    name: "portfolio",
    description: "This is my professional portfolio website",
    languages: "HTML, CSS, JavaScript",
    privacy: "Private",
    amountRemaining: "UGX 40000",
    people: [
      "https://picsum.photos/50?random=1",
      "https://picsum.photos/50?random=2",
      "https://picsum.photos/50?random=3",
      "https://picsum.photos/50?random=4",
      "https://picsum.photos/50?random=5",
      "https://picsum.photos/50?random=6",
    ],
  },
  {
    name: "blog",
    description: "A personal blog to share my thoughts and experiences",
    languages: "HTML, CSS, JavaScript, Node.js",
    privacy: "Public",
    amountRemaining: "UGX 70000",
    people: [
      "https://picsum.photos/50?random=7",
      "https://picsum.photos/50?random=8",
      "https://picsum.photos/50?random=9",
      "https://picsum.photos/50?random=10",
      "https://picsum.photos/50?random=11",
      "https://picsum.photos/50?random=12",
    ],
  },
  {
    name: "ecommerce-site",
    description: "An e-commerce website for selling products online",
    languages: "React, Node.js, MongoDB",
    privacy: "Private",
    amountRemaining: "UGX 10000",
    people: [
      "https://picsum.photos/50?random=13",
      "https://picsum.photos/50?random=14",
      "https://picsum.photos/50?random=15",
      "https://picsum.photos/50?random=16",
      "https://picsum.photos/50?random=17",
      "https://picsum.photos/50?random=18",
    ],
  },
  {
    name: "weather-app",
    description: "A weather forecasting app using external APIs",
    languages: "JavaScript, HTML, CSS, React",
    privacy: "Public",
    amountRemaining: "UGX 50000",
    people: [
      "https://picsum.photos/50?random=19",
      "https://picsum.photos/50?random=20",
      "https://picsum.photos/50?random=21",
      "https://picsum.photos/50?random=22",
      "https://picsum.photos/50?random=23",
      "https://picsum.photos/50?random=24",
    ],
  },
  {
    name: "task-manager",
    description: "A task management tool to organize daily tasks",
    languages: "Vue.js, Firebase",
    privacy: "Private",
    amountRemaining: "UGX 60000",
    people: [
      "https://picsum.photos/50?random=25",
      "https://picsum.photos/50?random=26",
      "https://picsum.photos/50?random=27",
      "https://picsum.photos/50?random=28",
      "https://picsum.photos/50?random=29",
      "https://picsum.photos/50?random=30",
    ],
  },
  {
    name: "chat-app",
    description: "A real-time chat application",
    languages: "Node.js, Socket.io, React",
    privacy: "Public",
    amountRemaining: "UGX 30000",
    people: [
      "https://picsum.photos/50?random=31",
      "https://picsum.photos/50?random=32",
      "https://picsum.photos/50?random=33",
      "https://picsum.photos/50?random=34",
      "https://picsum.photos/50?random=35",
      "https://picsum.photos/50?random=36",
    ],
  },
  {
    name: "recipe-app",
    description: "An app to find and share recipes",
    languages: "React, Node.js, MongoDB",
    privacy: "Private",
    amountRemaining: "UGX 20000",
    people: [
      "https://picsum.photos/50?random=37",
      "https://picsum.photos/50?random=38",
      "https://picsum.photos/50?random=39",
      "https://picsum.photos/50?random=40",
      "https://picsum.photos/50?random=41",
      "https://picsum.photos/50?random=42",
    ],
  },
  {
    name: "fitness-tracker",
    description: "An app to track fitness activities",
    languages: "React Native, Firebase",
    privacy: "Public",
    amountRemaining: "UGX 45000",
    people: [
      "https://picsum.photos/50?random=43",
      "https://picsum.photos/50?random=44",
      "https://picsum.photos/50?random=45",
      "https://picsum.photos/50?random=46",
      "https://picsum.photos/50?random=47",
      "https://picsum.photos/50?random=48",
    ],
  },
  {
    name: "expense-tracker",
    description: "An app to track personal expenses",
    languages: "Vue.js, Firebase",
    privacy: "Private",
    amountRemaining: "UGX 35000",
    people: [
      "https://picsum.photos/50?random=49",
      "https://picsum.photos/50?random=50",
      "https://picsum.photos/50?random=51",
      "https://picsum.photos/50?random=52",
      "https://picsum.photos/50?random=53",
      "https://picsum.photos/50?random=54",
    ],
  },
  {
    name: "music-streaming",
    description: "A music streaming service",
    languages: "React, Node.js, MongoDB",
    privacy: "Public",
    amountRemaining: "UGX 55000",
    people: [
      "https://picsum.photos/50?random=55",
      "https://picsum.photos/50?random=56",
      "https://picsum.photos/50?random=57",
      "https://picsum.photos/50?random=58",
      "https://picsum.photos/50?random=59",
      "https://picsum.photos/50?random=60",
    ],
  },
  {
    name: "social-network",
    description: "A social networking platform",
    languages: "React, Node.js, MongoDB",
    privacy: "Private",
    amountRemaining: "UGX 65000",
    people: [
      "https://picsum.photos/50?random=61",
      "https://picsum.photos/50?random=62",
      "https://picsum.photos/50?random=63",
      "https://picsum.photos/50?random=64",
      "https://picsum.photos/50?random=65",
      "https://picsum.photos/50?random=66",
    ],
  },
  {
    name: "news-aggregator",
    description: "An app to aggregate news from various sources",
    languages: "React, Node.js, MongoDB",
    privacy: "Public",
    amountRemaining: "UGX 25000",
    people: [
      "https://picsum.photos/50?random=67",
      "https://picsum.photos/50?random=68",
      "https://picsum.photos/50?random=69",
      "https://picsum.photos/50?random=70",
      "https://picsum.photos/50?random=71",
      "https://picsum.photos/50?random=72",
    ],
  },
];

export default repoDetails;
